Basic Data Types

In [2]:
import numpy as np

In [3]:
a = np.arange(10)

a.dtype

dtype('int64')

In [4]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
a = np.arange(10, dtype='float64')
a 

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [6]:
# The default data type is float for zeros and ones function 

a = np.zeros((3, 3))

print(a)

a.dtype

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


dtype('float64')

In [7]:
a = np.ones((3, 3))

print(a)

a.dtype

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


dtype('float64')

In [8]:
d = np.array([1 + 2j, 2 + 4j]) # complex datatype

print(d.dtype)

complex128


In [9]:
b = np.array([True, False, True, False]) # Boolean data type

print(b.dtype)

bool


In [10]:
s = np.array(["Varun", "Anup", "NSUT"])

s.dtype

dtype('<U5')

In [ ]:
# Each built in data type has a character code that uniquely identifies it.


'b' − boolean

'i' − (signed) integer

'u' − unsigned integer

'f' − floating-point

'c' − complex-floating point

'm' − timedelta

'M' − datetime

'O' − (Python) objects

'S', 'a' − (byte-)string

'U' − Unicode

'V' − raw data (void)

In [ ]:
# Indexing and Slicing 

In [11]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
print(a[5])

5


In [13]:
a = np.diag([1, 2, 3])
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [14]:
a[2,2]

3

In [15]:
a[1, 1]

2

In [16]:
a[2,1]

0

In [17]:
a[2, 1] = 5 #assigning value


In [18]:
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

In [19]:
# Slicing 
a = np.arange(10)
a 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
a[1:8:2] # start index, end index, step size


array([1, 3, 5, 7])

In [21]:
a[5:]

array([5, 6, 7, 8, 9])

In [22]:
a[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [23]:
a[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
a[::2]

array([0, 2, 4, 6, 8])

In [25]:
a[::4]

array([0, 4, 8])

In [26]:
a[-1]

9

In [27]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [29]:
b = np.arange(5)
b

array([0, 1, 2, 3, 4])

In [30]:
a[5:] = b[::-1] # assigning 

In [31]:
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [ ]:
# Copies and Views
# When modifiying the view, the original array is modified as well.

In [32]:
a = np.arange(10)
a 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
b = a[::2]
b 

array([0, 2, 4, 6, 8])

In [34]:
np.shares_memory(a, b)

True

In [35]:
b[0] = 10
b 

array([10,  2,  4,  6,  8])

In [36]:
a  # eventhough we modified b, it updated 'a because both shares same memory

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [37]:
a = np.arange(10)

c = a[::2].copy()  # force a copy
c 

array([0, 2, 4, 6, 8])

In [38]:
np.shares_memory(a, c)

False

In [39]:
c[0] = 10
c

array([10,  2,  4,  6,  8])

In [40]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Fancy Indexing
# Using Boolean Mask

In [41]:
a = np.random.randint(0, 20, 15)
a 

array([ 9,  1,  8,  2,  0,  2,  8,  9,  7,  3, 19, 10, 16, 17, 13])

In [42]:
mask = (a % 2 == 0)

In [43]:
extract_from_a = a[mask]
extract_from_a

array([ 8,  2,  0,  2,  8, 10, 16])

In [44]:
# Indexing with mask
a[mask] = -1
a 

array([ 9,  1, -1, -1, -1, -1, -1,  9,  7,  3, 19, -1, -1, 17, 13])

In [45]:
a = np.arange(0, 100, 10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [46]:
a[[2, 3, 2, 4, 2]] # Indexing can be done with an array of integers, where the same index is 
#repeated several times

array([20, 30, 20, 40, 20])

In [47]:
# New Values can be assigned 
a[[9, 7]] = 500

a 

array([  0,  10,  20,  30,  40,  50,  60, 500,  80, 500])